### ISSUE TITLE
Needs to be completed

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/ttt-6-position-taken-rb#1]
[Outline](https://github.com/learn-co-curriculum/ttt-6-position-taken-rb/blob/solution/README.md)

Also - i made it a bit more complicated but didn't spec it out. To force them to use an OR `||` we should give them a board with both `"   "` and `""` or something. Ping me about this.

**Comment by AnnJohn** [comment]
@aviflombaum just adding a deadline here for 9/10/15. feel free to adjust.

**Comment by aviflombaum** [comment]
Working on this now

**Comment by aviflombaum** [comment]
Pausing to review another PR

**Comment by aviflombaum** [comment]
Reviewing now.

**Comment by AnnJohn** [comment]
@aviflombaum going to set a deadline for today, 9/11/15 for this PR review

**Comment by aviflombaum** [comment]
I updated master with my review of new-content and now updating solution.

https://github.com/learn-co-curriculum/ttt-6-position-taken-rb/commit/d93af71b31dc91d16d6f09c48783667081bea089
