### ISSUE TITLE
consistent indexing in TTT

### ISSUE THREAD

**Issue by SoldierCoder** [learn-co-curriculum/ttt-6-position-taken-rb#13]
In previous versions of TTT the programmer was forced to subtract 1 from the position the player said.  In other words when the player said 1, he really meant to use index 0 to change the first element of the array.  I made an update to the directions for this lesson to make clear that that is no longer the case.

**Comment by AnnJohn** [comment]
Thanks @SoldierCoder! Merged your PR.
