### ISSUE TITLE
Ask a question?

### ISSUE THREAD

**Issue by jonpstone** [learn-co-curriculum/ttt-6-position-taken-rb#27]
I rarely ever see the 'Ask a question" button in any of the lessons.

**Comment by AnnJohn** [comment]
Hi @jonpstone could you please file a bug report for this If you hover over your profile pic you'll see an option for that. You should be able to see the 'Ask a Question' button so this looks like a product/technical issue. Thanks.

**Comment by jonpstone** [comment]
Hi, don't worry, I actually think it's got something to do with the internet at work (I work security). It works fine at home, it's good to know I can use the profile pic option though. Thanks. 

```
On Tuesday, February 23, 2016 10:14 AM, AnnJohn <notifications@github.com> wrote:
```

 Hi @jonpstone could you please file a bug report for this If you hover over your profile pic you'll see an option for that. You should be able to see the 'Ask a Question' button so this looks like a product/technical issue. Thanks. —
