### ISSUE TITLE
lesson addition suggestion

### ISSUE THREAD

**Issue by lowenergy** [learn-co-curriculum/ttt-6-position-taken-rb#29]
Did not want to edit the lesson, but I think this subject should be added to the lesson.  It concerns the "string listed in condition" warning you can receive if you just have a string value by itself in an "if" method.  EX:  board[position] = "x" || "O" .  This works correctly to pass the test by itself but when used with the other "if" statement (that by itself passes the first three tests) then it fails.  As you know, this is a result of the string "O" by itself.  This drove me nuts for about an hour because it made no sense why my statements worked separately but not together.  I finally had to Google the string listed in condition warning to realize how to fix it.  I just think this should be mentioned in the lesson.  Thanks.

**Comment by aturkewi** [comment]
Hey @lowenergy I'm a little unclear about the issue you were running into. Could you post the code that was causing this error so I can better understand it and make an update to the lab?
