### ISSUE TITLE
if/else statements haven't been covered yet in this track

### ISSUE THREAD

**Issue by AnnJohn** [learn-co-curriculum/ttt-6-position-taken-rb#3]
Need to have either a new lesson or existing content on if/else statements prior to this lab for students to be able to complete it

**Comment by aviflombaum** [comment]
Ya, this is my bad. Originally this lab was easy to solve using boolean login `||` and no `if` statements were required. I guess we'll just move it farther down the track.

**Comment by AnnJohn** [comment]
@aviflombaum the next lesson actually covers it. i can move it further down after going through this unit

**Comment by aviflombaum** [comment]
I reorganized this unit to reflect this.
