### ISSUE TITLE
Stuck on Tic Tac Toe Position Taken

### ISSUE THREAD

**Issue by anglinchristina** [learn-co-curriculum/ttt-6-position-taken-rb#34]
I have read through the rspec files and I haven't figured out why I am getting this error:

5 examples, 1 failure                                                                                             

Failed examples:                                                                                                  

rspec ./spec/position_taken_spec.rb:35 # #position_taken? in lib/position_taken.rb returns true if the board has a
 value of "X" or "O" in the index                

Here's what's in my lib/position_taken.rb file:

def position_taken?(board, index)
  if board[index] == " " || "" || nil
    false
  elsif board[index] == 'X' || 'O'
    true
  end
end

**Comment by AnnJohn** [comment]
hi @anglinchristina since this is a question specific to your code, please use the Ask a Question tool we have in Learn and someone from our team will help you out. Thanks!
