### ISSUE TITLE
Small spelling error 

### ISSUE THREAD

**Issue by InfoSecTyler** [learn-co-curriculum/ttt-6-position-taken-rb#37]
Just noticed a small spelling error on the GIF caption for this lesson in the IDE. The current caption reads: robot doesn't know positio_take? I think it was intended to be position_taken; as this is the method we are creating in this lesson. 

Not a huge error, just happened to catch my eye. Thanks!

**Comment by gj** [comment]
Fixed in c955691. Thanks @InfoSecTyler !
