### ISSUE TITLE
Lab introduces ternary operators somewhat incorrectly

### ISSUE THREAD

**Issue by AnnJohn** [learn-co-curriculum/ttt-6-position-taken-rb#4]
Lab introduces ternary operators by saying that to complete this lab a variable needs to be created in the method outside of the if/else statements. (Screenshot below)

![screen shot 2015-09-29 at 10 08 41 am](https://cloud.githubusercontent.com/assets/1892150/10166484/3f879000-6692-11e5-91b1-f995d6bcbbbd.png)

But tests can pass without having to use a variable- solution below:

![screen shot 2015-09-29 at 10 12 56 am](https://cloud.githubusercontent.com/assets/1892150/10166581/b5819184-6692-11e5-9341-298604d2587f.png)

So either ternary operators should be introduced in another way. Or can we just not mention them at all since a student can solve this lab without needing to know it.

**Comment by aviflombaum** [comment]
closed by f5fe76d4e866df5c878729b1662c4baac52fbc02
