### ISSUE TITLE
[SE Issue] 

### ISSUE THREAD

**Issue by Raymond1028** [learn-co-curriculum/ttt-6-position-taken-rb#45]
### Canvas Link

https://github.com/Raymond1028/ttt-6-position-taken-rb

### Concern

The chat icon for help with a TC has disappeared from my lessons.

**Comment by ihollander** [comment]
Hi @Raymond1028, thanks for flagging this! One thing to be aware of is that the Pair with a TC feature is only available Monday through Friday, 9AM to 1AM ET, and Saturday and Sunday, 9AM to 12AM ET, and is also not available during some holidays: https://flatironschoolsupport.zendesk.com/hc/en-us/articles/1500005525241-When-are-Online-SE-Technical-Coaches-available-

Could you please include a link to the page in Canvas where you expected to find the Pair with a TC button? The URL should start with https://learning.flatironschool.com/

**Comment by Raymond1028** [comment]
My green check are not appearing after successful completion of work. Thanks

**Comment by ihollander** [comment]
@Raymond1028 sorry I didn't see your reply! I'm closing this issue since it looks like your other issue is not related. Can you please open a new issue on the lesson that isn't showing the green check mark, and provide more context?
