### ISSUE TITLE
Part III refers to setting value of a variable

### ISSUE THREAD

**Issue by matbalez-zz** [learn-co-curriculum/ttt-6-position-taken-rb#5]
Part III (refactoring) says the following: 

"So far, our code leaves a little something to be desired. We are using an if/else statement that requires us to set a variable, taken, outside of the if/else statement, modify that variable and then return the variable at the end of the method. That's a lot of code to answer the simple question: "is this position taken?""

The user hasn't seen the solution code at this point. The above presupposes that the user is using conditional logic in such a way that they are assigning a value to a variable "taken". When I coded my solution I didn't use a variable, I did the following: 

def position_taken?(board, pos)
  if (board[pos] == " ") || (board[pos] == "") || (board[pos] == nil)
    false
  else
    true
  end
end

and so I found the presupposition confusing.

**Comment by AnnJohn** [comment]
raised same issue #4

**Comment by aviflombaum** [comment]
closed by f5fe76d4e866df5c878729b1662c4baac52fbc02
